name: Seed and build test configurations of the ODK

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/seed-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/seed-tests.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We run the seeding tests using a "native" ODK environments;
        # those will never be supported on Windows, but they SHOULD
        # work on x86 GNU/Linux and both x86 and arm64 macOS.
        os: [ ubuntu-latest, macos-15, macos-15-intel ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Create dummy Git user name
        run: git config --global user.name Alice
      - name: Create dummy Git user email
        run: git config --global user.email alice@example.org
      - name: Install Python dependencies
        run: uv sync --all-extras
      - name: Run the tests
        run: cd tests && sh test-config.sh
